### ISSUE TITLE
日语字幕?

### ISSUE THREAD

**Issue by Javran** [kcwikizh/kcwiki-api#2]
想问下是否有类似 http://api.kcwiki.moe/subtitles 这样的接口获取日语字幕? 若没有的话是否能考虑实现呢?

**Comment by grzhan** [comment]
为了做校对（[http://revise.kcwiki.moe/v2/](http://revise.kcwiki.moe/v2/)）有做日语数据抓取的逻辑，如果需要的话我马上加一下

**Comment by Javran** [comment]
@grzhan 嗯,希望能加个这样的接口. 此外能否用和subtitles一样的格式呢?

**Comment by grzhan** [comment]
接口： [http://api.kcwiki.moe/subtitles/jp](http://api.kcwiki.moe/subtitles/jp) , [http://api.kcwiki.moe/subtitles/jp/{shipId}](http://api.kcwiki.moe/subtitles/jp/1)

最近一段时间比较忙，现在才上线抱歉。

之后会写下现有的API的文档

**Comment by Javran** [comment]
辛苦了,非常感觉!

**Comment by grzhan** [comment]
@Javran 忘记讲了，前段时间给日文也添加了差分接口，具体可以参考本项目的API说明文档：[https://github.com/kcwikizh/kcwiki-api#324-i18n](https://github.com/kcwikizh/kcwiki-api#324-i18n)

**Comment by Javran** [comment]
@grzhan 了解.  cc @sinsinpub
